![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)
#### NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* A powerful N-dimensional array object
* Sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Useful linear algebra, Fourier transform, and random number capabilities

Numpy is a powerfull set of tools to perform mathematical operations of on lists of numbers. Numpy is faster than python and is builds on (and is a successor to) the successful Numeric array object. Its goal is to create the corner-stone for a useful environment for scientific computing.

### Import The Library 
First, You have to import Numpy as np. This helps writing code and it's almost a standard in scientific work.

In [5]:
import numpy as np

#### Working With ndarray 
"An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size."
#### Generate ndarray with arange method.
np.arange([start,]stop[,step,], dtype=none)

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [14]:
np.arange(1,10,3)

array([1, 4, 7])

In [15]:
np.arange(1,10,2,dtype=np.float64)

array([1., 3., 5., 7., 9.])

#### Examine the ndarray

In [21]:
arr = np.arange(1,20,4)
arr.ndim # outputs the number of dimensions of the array

1

In [20]:
arr.shape #dimension size [(5,0)]

(5,)

In [22]:
arr.size # size of the array

5

In [23]:
arr.dtype # the data type of the array

dtype('int32')

In [24]:
arr.itemsize # Tells the size of each item inside the array

4

In [25]:
#Memory Usage
arr.size * arr.itemsize # Gets the value in bytes 

20

#### Links
http://www.numpy.org/
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html